version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sim-absensi
    container_name: sim-absensi
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - postgres
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: sim-absensi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
