version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - postgres
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: s_
